### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code: received unknown error (no such frame) for NOT_FOUND status code'

### ISSUE THREAD

**Issue by Pure-arc** [stevepryde/thirtyfour#183]
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code: received unknown error (no such frame) for NOT_FOUND status code', C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\fantoccini-0.19.3\src\session.rs:905:34
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:67
   2: fantoccini::session::impl$5::issue_wd_cmd::closure$2<hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector<hyper::client::connect::dns::GaiResolver> >,dyn$<fantoccini::wd::WebDriverCompatibleCommand,core::marker::Send> >
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\fantoccini-0.19.3\src\session.rs:905
   3: futures_util::fns::impl$0::call_once<fantoccini::session::impl$5::issue_wd_cmd::closure_env$2<hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector<hyper::client::connect::dns::GaiResolver> >,dyn$<fantoccini::wd::WebDriverCom
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-util-0.3.28\src\fns.rs:15
   4: futures_util::future::future::map::impl$2::poll<futures_util::future::future::Map<futures_util::future::try_future::AndThen<futures_util::future::try_future::MapErr<hyper::client::client::ResponseFuture,enum2$<fantoccini::error::CmdError> (*)(hyper::error
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-util-0.3.28\src\future\future\map.rs:57
   5: futures_util::future::future::impl$15::poll<futures_util::future::future::Map<futures_util::future::try_future::AndThen<futures_util::future::try_future::MapErr<hyper::client::client::ResponseFuture,enum2$<fantoccini::error::CmdError> (*)(hyper::error::Er
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-util-0.3.28\src\lib.rs:91
   6: futures_util::future::either::impl$4::poll<futures_util::future::future::Map<futures_util::future::future::Map<futures_util::future::try_future::AndThen<futures_util::future::try_future::MapErr<hyper::client::client::ResponseFuture,enum2$<fantoccini::erro
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-util-0.3.28\src\future\either.rs:109
   7: enum2$<fantoccini::session::Ongoing>::poll
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\fantoccini-0.19.3\src\session.rs:383
   8: fantoccini::session::impl$4::poll<hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector<hyper::client::connect::dns::GaiResolver> > >
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\fantoccini-0.19.3\src\session.rs:448
   9: tokio::runtime::task::core::impl$6::poll::closure$0<fantoccini::session::Session<hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector<hyper::client::connect::dns::GaiResolver> > >,alloc::sync::Arc<tokio::runtime::scheduler::
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\core.rs:334
  10: tokio::loom::std::unsafe_cell::UnsafeCell<enum2$<tokio::runtime::task::core::Stage<fantoccini::session::Session<hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector<hyper::client::connect::dns::GaiResolver> > > > > >::with_m
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\loom\std\unsafe_cell.rs:16
  11: tokio::runtime::task::core::Core<fantoccini::session::Session<hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector<hyper::client::connect::dns::GaiResolver> > >,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handl
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\core.rs:323
  12: tokio::runtime::task::harness::poll_future::closure$0<fantoccini::session::Session<hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector<hyper::client::connect::dns::GaiResolver> > >,alloc::sync::Arc<tokio::runtime::scheduler
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\harness.rs:485
  13: core::panic::unwind_safe::impl$23::call_once<enum2$<core::task::poll::Poll<tuple$<> > >,tokio::runtime::task::harness::poll_future::closure_env$0<fantoccini::session::Session<hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnec
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\panic\unwind_safe.rs:271
  14: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<fantoccini::session::Session<hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector<hyper::clien
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\panicking.rs:500
  15: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$1<futures_util::future::future::Map<futures_util::future::poll_fn::PollFn<hyper::client::client::impl$3::send_request::async_f
  16: std::panicking::try<enum2$<core::task::poll::Poll<tuple$<> > >,core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<fantoccini::session::Session<hyper_rustls::connector::HttpsConnector<hyper::client::connect
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\panicking.rs:464
  17: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<fantoccini::session::Session<hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector<hyper::client::c
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\panic.rs:142
  18: tokio::runtime::task::harness::poll_future<fantoccini::session::Session<hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector<hyper::client::connect::dns::GaiResolver> > >,alloc::sync::Arc<tokio::runtime::scheduler::multi_thr
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\harness.rs:473
  19: tokio::runtime::task::harness::Harness<fantoccini::session::Session<hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector<hyper::client::connect::dns::GaiResolver> > >,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread:
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\harness.rs:208
  20: tokio::runtime::task::harness::Harness<fantoccini::session::Session<hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector<hyper::client::connect::dns::GaiResolver> > >,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread:
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\harness.rs:153
  21: tokio::runtime::task::raw::poll<fantoccini::session::Session<hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector<hyper::client::connect::dns::GaiResolver> > >,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\raw.rs:276
  22: tokio::runtime::task::raw::RawTask::poll
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\raw.rs:200
  23: tokio::runtime::task::LocalNotified<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle> >::run<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle> >
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\mod.rs:400
  24: tokio::runtime::scheduler::multi_thread::worker::impl$1::run_task::closure$0
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\scheduler\multi_thread\worker.rs:639
  25: tokio::runtime::coop::with_budget
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\coop.rs:107
  26: tokio::runtime::coop::budget
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\coop.rs:73
  27: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\scheduler\multi_thread\worker.rs:575
  28: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\scheduler\multi_thread\worker.rs:526
  29: tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure$0
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\scheduler\multi_thread\worker.rs:491
  30: tokio::runtime::context::scoped::Scoped<enum2$<tokio::runtime::scheduler::Context> >::set<enum2$<tokio::runtime::scheduler::Context>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0,tuple$<> >
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\context\scoped.rs:40
  31: tokio::runtime::context::set_scheduler::closure$0<tuple$<>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0>
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\context.rs:176
  32: std::thread::local::LocalKey<tokio::runtime::context::Context>::try_with<tokio::runtime::context::Context,tokio::runtime::context::set_scheduler::closure_env$0<tuple$<>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0>,tuple$
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\thread\local.rs:270
  33: std::thread::local::LocalKey<tokio::runtime::context::Context>::with<tokio::runtime::context::Context,tokio::runtime::context::set_scheduler::closure_env$0<tuple$<>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0>,tuple$<> >
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\thread\local.rs:246
  34: tokio::runtime::context::set_scheduler<tuple$<>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0>
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\context.rs:176
  35: tokio::runtime::scheduler::multi_thread::worker::run::closure$0
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\scheduler\multi_thread\worker.rs:486
  36: tokio::runtime::context::runtime::enter_runtime<tokio::runtime::scheduler::multi_thread::worker::run::closure_env$0,tuple$<> >
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\context\runtime.rs:65
  37: tokio::runtime::scheduler::multi_thread::worker::run
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\scheduler\multi_thread\worker.rs:478
  38: tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure$0
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\scheduler\multi_thread\worker.rs:447
  39: tokio::runtime::blocking::task::impl$2::poll<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0,tuple$<> >
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\blocking\task.rs:42
  40: tokio::runtime::task::core::impl$6::poll::closure$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\core.rs:334
  41: tokio::loom::std::unsafe_cell::UnsafeCell<enum2$<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0> > > >::with_mut
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\loom\std\unsafe_cell.rs:16
  42: tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>::poll<tokio::runtime::blocking::task::Block
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\core.rs:323
  43: tokio::runtime::task::harness::poll_future::closure$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\harness.rs:485
  44: core::panic::unwind_safe::impl$23::call_once<enum2$<core::task::poll::Poll<tuple$<> > >,tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch:
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\panic\unwind_safe.rs:271
  45: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\panicking.rs:500
  46: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<std::sys::common::thread_local::fast_local::destroy_value::closure_env$0<tokio::runtime::park::ParkThread> >,tuple$<> >
  47: std::panicking::try<enum2$<core::task::poll::Poll<tuple$<> > >,core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worke
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\panicking.rs:464
  48: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,toki
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\panic.rs:142
  49: tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\harness.rs:473
  50: tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>::poll_inner<tokio::runtime::blocking:
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\harness.rs:208
  51: tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>::poll<tokio::runtime::blocking::task:
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\harness.rs:153
  52: tokio::runtime::task::raw::poll<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\raw.rs:276
  53: tokio::runtime::task::raw::RawTask::poll
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\raw.rs:200
  54: tokio::runtime::task::UnownedTask<tokio::runtime::blocking::schedule::BlockingSchedule>::run<tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\task\mod.rs:437
  55: tokio::runtime::blocking::pool::Task::run
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\blocking\pool.rs:159
  56: tokio::runtime::blocking::pool::Inner::run
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\blocking\pool.rs:513
  57: tokio::runtime::blocking::pool::impl$6::spawn_thread::closure$0
             at C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.32.0\src\runtime\blocking\pool.rs:471
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by newestera** [comment]
match driver.enter_frame(0).await {
        Ok(_) => {
            let iframe_source = driver.source().await?;
            complete_body.push(iframe_source)
        }
        Err(_) => {}
    }

**Comment by stevepryde** [comment]
We'll need to check if the same thing happens with fantoccini. Are you able to try it?

Also what webdriver were you running against?

**Comment by newestera** [comment]
i tried same thing is happening with fantoccini. 

thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code: received unknown error (no such frame) for NOT_FOUND status code', C:\Users\Heap\.cargo\registry\src\index.crates.io-6f17d22bba15001f\fantoccini-0.19.3\src\session.rs:905:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

i am using chromedriver

**Comment by stevepryde** [comment]
Does this still happen on the latest version? The backend has been rewritten since this ticket was created.

**Comment by vrtgs** [comment]
I second this, Does this still happen on the latest version?

**Comment by stevepryde** [comment]
Closing. Reopen if this is still happening on latest
